// Generated by CoffeeScript 1.8.0
(function() {
  var ArticleSave, rule, schedule;

  ArticleSave = require('../servers/saveArticle');

  schedule = require("node-schedule");

  rule = new schedule.RecurrenceRule();

  rule.minute = 30;

  schedule.scheduleJob(rule, function() {
    var a;
    a = new ArticleSave();
    return a.getPage(1, function() {
      return console.log("ok");
    });
  });

}).call(this);

//# sourceMappingURL=test-save.js.map
