// Generated by CoffeeScript 1.10.0
(function() {
  var ArticleSave, rule1, schedule;

  ArticleSave = require('../servers/saveArticle');

  schedule = require("node-schedule");

  rule1 = new schedule.RecurrenceRule();

  rule1.dayOfWeek = [0, new schedule.Range(1, 6)];

  rule1.hour = 20;

  rule1.minute = 10;

  schedule.scheduleJob(rule1, function() {
    var a;
    a = new ArticleSave();
    return a.getPage(1, function() {
      return console.log("ok");
    });
  });

}).call(this);

//# sourceMappingURL=test-save.js.map
