// Generated by CoffeeScript 1.8.0
(function() {
  var ArticleSave, a;

  ArticleSave = require('../servers/saveArticle');

  a = new ArticleSave();

  a.getPage(1, function() {
    return console.log("ok");
  });

}).call(this);

//# sourceMappingURL=test-save.js.map
