// Generated by CoffeeScript 1.8.0
(function() {
  var express, router;

  express = require('express');

  router = express.Router();


  /* GET users listing. */

  router.get('/', function(req, res, next) {
    return res.render('users');
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=users.js.map
