// Generated by CoffeeScript 1.8.0
(function() {
  var Article, PushUser, User, async, express, router, saveErr;

  express = require('express');

  PushUser = require('../servers/pushUser');

  Article = require('../models/article');

  User = require('../models/user');

  async = require('async');

  saveErr = require('../servers/saveErr');

  router = express.Router();


  /* GET users listing. */

  router.get('/', function(req, res, next) {
    return Article.count({}, function(err, count) {
      var subscribe, title;
      if (err) {
        return saveErr("", 2, {
          err: err
        });
      }
      title = "Pocket连接管理";
      subscribe = req.session.subscribe;
      return res.render('users', {
        title: title,
        subscribe: subscribe,
        count: count
      });
    });
  });

  router.get('/subscribe', function(req, res) {
    var subscribe, username;
    username = req.session.username;
    subscribe = req.session.subscribe;
    return User.findOne({
      username: username
    }, function(err, row) {
      if (err) {
        return saveErr("", 2, {
          err: err
        });
      }
      if (!row) {
        req.session.error = "没有找到用户";
        return res.redirect('/');
      }
      if (subscribe === true) {
        subscribe = false;
      } else {
        subscribe = true;
      }
      row.subscribe = subscribe;
      return row.save(function(err2, row2) {
        if (err2) {
          return saveErr("", 2, {
            err: err2
          });
        }
        req.session.subscribe = subscribe;
        return res.redirect('/');
      });
    });
  });

  router.get('/push', function(req, res) {
    var p, username;
    username = req.session.username;
    p = new PushUser(username);
    return async.series([
      function(cb) {
        return p.getToken(function(err) {
          if (err) {
            return console.log(err);
          }
          return cb();
        });
      }, function(cb) {
        return p.getArticle(function(err) {
          if (err) {
            return console.log(err);
          }
          return cb();
        });
      }, function(cb) {
        return p.pushInfo(function(err) {
          if (err) {
            return console.log(err);
          }
          req.session.success = "推送成功";
          return res.redirect('/users');
        });
      }
    ]);
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=users.js.map
