// Generated by CoffeeScript 1.8.0
(function() {
  var PushUser, async, express, router;

  express = require('express');

  PushUser = require('../servers/pushUser');

  async = require('async');

  router = express.Router();


  /* GET users listing. */

  router.get('/', function(req, res, next) {
    return res.render('users');
  });

  router.get('/push', function(req, res) {
    var p, username;
    username = req.session.username;
    p = new PushUser(username);
    return async.series([
      function(cb) {
        return p.getToken(function(err) {
          if (err) {
            return console.log(err);
          }
          return cb();
        });
      }, function(cb) {
        return p.getArticle(function(err) {
          if (err) {
            return console.log(err);
          }
          return cb();
        });
      }, function(cb) {
        return p.pushInfo(function(err) {
          if (err) {
            return console.log(err);
          }
          req.session.success = "推送成功";
          return res.redirect('/users');
        });
      }
    ]);
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=users.js.map
