// Generated by CoffeeScript 1.8.0
(function() {
  var Article, PushUser, User, async, request, saveErr;

  request = require('request');

  async = require('async');

  User = require('../models/user');

  Article = require('../models/article');

  saveErr = require("../servers/saveErr");

  PushUser = (function() {
    function PushUser(username) {
      this.username = username;
      this.token = '';
      this.articleArr = [];
    }

    PushUser.prototype.getToken = function(cb) {
      var self;
      self = this;
      return User.findOne({
        username: self.username
      }, function(err, row) {
        if (err) {
          return console.log(err);
        }
        if (!row) {
          return cb("没有找到此用户");
        } else {
          self.token = row.token;
          return cb();
        }
      });
    };

    PushUser.prototype.getArticle = function(cb) {
      var self;
      self = this;
      return Article.find(function(err, rows) {
        if (err) {
          return console.log(err);
        }
        self.articleArr = rows;
        return cb();
      });
    };

    PushUser.prototype.pushInfo = function(cb) {
      var self;
      self = this;
      return async.eachLimit(self.articleArr, 20, function(item, callback) {
        var form, op;
        form = {
          url: item.url,
          title: item.title,
          tags: 'Cnode',
          consumer_key: process.env.pocket,
          access_token: self.token
        };
        op = {
          form: form,
          url: 'https://getpocket.com/v3/add'
        };
        return request.post(op, function(err, res, body) {
          var data;
          if (err) {
            return console.log(err);
          }
          try {
            data = JSON.parse(body);
          } catch (_error) {
            return saveErr(op.url, 3, {
              err: body
            });
          }
          console.log(data.item.normal_url);
          return callback();
        });
      }, function() {
        console.log("##### all dododo #####");
        return cb();
      });
    };

    return PushUser;

  })();

  module.exports = PushUser;

}).call(this);

//# sourceMappingURL=pushUser.js.map
