// Generated by CoffeeScript 1.8.0
(function() {
  var UserSchema, mongoose;

  mongoose = require('./mongoose');

  UserSchema = mongoose.Schema({
    username: String,
    created: Number,
    token: String,
    subscribe: Boolean
  });

  module.exports = mongoose.model('User, UserSchema');

}).call(this);

//# sourceMappingURL=user.js.map
